version: "3.9"
services:
  frontend:
    container_name: phonemarkt-app
    image: phonemarkt-app/v1.0.0
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL='https://itx-frontend-test.onrender.com'
      - VITE_API_PRODUCTS_URL='/api/product/'
      - VITE_API_PRODUCT_CART='/api/cart/'

networks:
  frontend:
    name: phonemarkt